name: Update app
on:
  workflow_dispatch:
    inputs:
      stage:
        type: choice
        description: 'Stage'
        required: true
        options:
          - integration
          - acceptance
          - productive
        default: 'integration'

jobs:
  update-values:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Check stuped
        run: |
          if [[ ! "${GITHUB_REF}" =~ ^refs/heads/release/ ]]; then
            echo "Error: The branch name must follow the release/** pattern."
            exit 1
          fi

      - name: Checkout main-repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Extract version from pom.xml
        id: extract_version
        run: |
          version=$(awk '/<artifactId>playground<\/artifactId>/,/<\/project>/' pom.xml | grep -oPm1 "(?<=<version>)[^<]+")
          echo "version=$version" >> $GITHUB_ENV

      - name: Checkout hc-repository
        uses: actions/checkout@v4
        with:
          repository: 'jksevend-trimble/example-hc'
          path: 'example-hc'
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Update values.yaml
        run: |
          declare -A stage_map=( ["integration"]="in" ["acceptance"]="ac" ["productive"]="pd" )
          short_stage_name=${stage_map[${{ inputs.stage }}]}
          echo "short_stage_name=$short_stage_name" >> $GITHUB_ENV
          version=${{ env.version }}
          sed -i "s/tag: .*/tag: $version/" example-hc/envs/$short_stage_name/values.yaml

      - name: Commit changes
        run: |
          cd example-hc
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b update/${{ inputs.stage }}/${{ env.version }}
          git add envs/${{ env.short_stage_name }}/values.yaml
          git commit -m "chore: Update version to ${{ env.version}} for '${{ inputs.stage }}' from '${{ github.ref }}' "
          git push https://jksevend-trimble:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/jksevend-trimble/example-hc.git update/${{ inputs.stage }}/${{ env.version }}

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          gh pr create --repo jksevend-trimble/example-hc \
            --head update/${{ inputs.stage }}/${{ env.version }} \
            --base main \
            --title "[${{ inputs.stage }}]: update v${{ env.version }}" \
            --body "Update ${{github.repository_id}} [${{ inputs.stage }}] to v${{ env.version }}"